---
title: "Code_A_Thon_Project"
author: "Chelsea"
date: "2024-10-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r library, include= FALSE}
library(tidyverse)
library(Hmisc)
library(foreign)
library(ggplot2)
library(finalfit)
library(forcats)
library(haven)
library(dplyr)
library(readxl)
library(SOAR)
suppressMessages(library(tidyverse))
suppressMessages(library(Hmisc))
suppressMessages(library(lubridate))
library(injuryepi)
library(overdoser)
library(rvdrs)
library(maps)
library(stringr)
library(tidygeocoder)
```



```{r, include=FALSE}
#load environment
load("S:/PCH/OHC/IVP/InjuryEpi/suicide/WA-VDRS Data/WA-VDRS Data/VDRS2022_Data.RData")
```

Combine data with mapping data
```{r}
#mapping data
zip_wa <- zctas(state = "WA", year = 2010)



#clean county name in VDRS data
wa_nvdrs22_comp$ResidenceFIPS<- gsub(", WA","",wa_nvdrs22_comp$ResidenceFIPS)
head(wa_nvdrs22_comp$ResidenceFIPS)

wa_nvdrs22_comp$ResidenceState<- gsub("Washington","53",wa_nvdrs22_comp$ResidenceState)
head(wa_nvdrs22_comp$ResidenceState)
#wa_nvdrs22_comp<- wa_nvdrs22_comp %>% mutate(str_to_lower(ResidenceFIPS),
#                                              str_to_lower(ResidenceState))
# wa_nvdrs22_comp<-wa_nvdrs22_comp %>% rename(region=ResidenceState, subregion=county, order=ResidenceZip)
# head(wa_nvdrs22_comp$subregion)

# wa_nvdrs22_comp$subregion <- str_to_lower(wa_nvdrs22_comp$subregion)
# wa_nvdrs22_comp$region <- str_to_lower(wa_nvdrs22_comp$region)
# head(wa_nvdrs22_comp$subregion)
# head(wa_nvdrs22_comp$region)

#subgroup VDRS data to needed variables
suicide_cir<-c("ResidenceState","ResidenceFIPS", "ResidenceZip", "IncidentYear_chr","IncidentNumber", "Sex", "RaceEthnicity_c","AgeYears_c", "Military", "RelationshipStatus", "AbstractorDeathmanner_c", "MentalHealthProblem_c", "DepressedMood_c", "AlcoholProblem_c", "MentalIllnessTreatmentCurrnt_c", "HistoryMentalIllnessTreatmnt_c", "IntimatePartnerProblem_c", "Argument_c", "SuicideThoughtHistory_c", "SuicideAttemptHistory_c", "HistorySelfHarm_c", "SuicideIntentDisclosed_c", "DisclosedToIntimatePartner_c", "DisclosedToOtherFamilyMember_c", "DisclosedToHealthCareWorker_c", "DisclosedToFriend_c", "DisclosedToNeighbor_c", "DisclosedToSocialMedia_c", "SuicideNote_c", "PhysicalHealthProblem_c", "JobProblem_c", "FinancialProblem_c", "SchoolProblem_c", "EvictionOrLossOfHome_c", "WeaponType1")

#suicide only data
wa_nvdrs22_comp_suicidecir<-wa_nvdrs22_comp %>% 
  filter(AbstractorDeathmanner_c == "Suicide or intentional self-harm") %>% 
  filter(IncidentYear>=2018) %>% 
  filter(ResidenceState=="53") %>% 
  select(suicide_cir) 
  
wa_nvdrs22_comp_suicidecir %>% is.na("ResidenceZip")#looking for na values in this varuable so we can drop them or replace them
```


Summarizing data for mental health problems by zip code
```{r}
wa_nvdrs22_suicidecir_MHP<-wa_nvdrs22_comp_suicidecir %>% 
  select(c("ResidenceState","ResidenceFIPS", "ResidenceZip", "IncidentYear_chr","MentalHealthProblem_c","DepressedMood_c")) %>% 
  mutate(ResidenceZip=ifelse(is.na(ResidenceZip),99999,ResidenceZip)) %>% 
  mutate(mentaldepressed= case_when(MentalHealthProblem_c=="Yes"|DepressedMood_c=="Yes"~'Yes',
                                                          TRUE~ 'No, Not Available, Unknown'))

#change zip codes with 0 value to unknown value of 99999
wa_nvdrs22_suicidecir_MHP %>% count(ResidenceZip)
wa_nvdrs22_suicidecir_MHP %>% count(ResidenceZip!="0",IncidentYear_chr)
wa_nvdrs22_suicidecir_MHP[wa_nvdrs22_suicidecir_MHP$ResidenceZip==0, "ResidenceZip"]<-99999
wa_nvdrs22_suicidecir_MHP %>% count(ResidenceZip)


wa_nvdrs22_suicidecir_MHP2<-wa_nvdrs22_suicidecir_MHP %>% group_by(ResidenceZip) %>% 
  count(mentaldepressed) %>% 
  filter(mentaldepressed=="Yes")



```


Combining the Mapping data
```{r}
wa_nvdrs22_suicidecir_MHP2<-wa_nvdrs22_suicidecir_MHP2 %>% mutate(ResidenceZip=as.character(ResidenceZip))

wa_nvdrs22_mh_map<-left_join(zip_wa,wa_nvdrs22_suicidecir_MHP2,by=join_by(ZCTA5CE10==ResidenceZip))

```


Attempting to map?
```{r}
ggplot(data = wa_nvdrs22_mh_map, aes(fill = n)) + 
  geom_sf()
```


County level data
```{r}
library(tigris)

wa_counties<-counties(state = "WA", cb= TRUE)
  
#checking NAs'in county data
table(wa_nvdrs22_suicidecir_MHP$ResidenceFIPS)
wa_nvdrs22_suicidecir_MHP %>% pull(ResidenceFIPS) %>% is.na()


#getting county level counts
wa_nvdrs22_suicidecir_MHP3<-wa_nvdrs22_suicidecir_MHP %>% group_by(ResidenceFIPS) %>% 
  count(mentaldepressed) %>% 
  filter(mentaldepressed=="Yes")
```

Combine county data with maping data
```{r}
wa_nvdrs22_mh_countymap<-left_join(wa_counties,wa_nvdrs22_suicidecir_MHP3,by=join_by(NAME==ResidenceFIPS))
wa_nvdrs22_mh_countymap

```


Mapping County Level
```{r}
library(esquisse)
esquisser(wa_nvdrs22_mh_countymap)

ggplot(wa_nvdrs22_mh_countymap) +
  aes(fill = n) +
  geom_sf() +
  scale_fill_distiller(palette = "GnBu", direction = -1) +
  theme_void()

```

looking at data based on % out of cases
```{r}

#changing MD variable into 



#to get the % out of MHD for cases
wa_nvdrs22_suicidecir_MHP %>% group_by() %>% 
  psum(md)/n()



```

